version: "3"

services:
  celephaisbot:
    image: ctjinx/celephaisbot:latest
    environment:
      - REDISTOGO_URL=redis:celephaisbot-redis:6379
    env_file: .env
    networks:
      - celephaisnet
    depends_on:
      - celephaisbot-redis

  celephaisbot-redis:
    image: redis:5.0.3-alpine
    networks:
      - celephaisnet
    volumes:
      - "./data/:/data/"

networks:
  celephaisnet:
